language: ruby
sudo: false

cache:
  bundler: true

addons:
  postgresql: "9.4"

bundler_args: --without test --jobs 1 --retry 3

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update

rvm:
  - 2.3.0
  - ruby-head
