language: ruby
sudo: false

cache:
  bundler: true
  directories:
  - vendor/bundle
  - node_modules
addons:
  postgresql: "9.4"

before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update

rvm:
  - 2.3.0
  - ruby-head
