language: ruby
sudo: false

rvm:
  - 2.3.1
  # Removing ruby-head (2.4.0) for now since our Gemfile is locked at 2.3.1
  # - ruby-head

services: postgresql

bundler_args: --without production development --binstubs --jobs 3 --retry 3

<<<<<<< HEAD
before_install: gem install bundler -v 1.12.25
=======
before_install: gem install bundler -v 1.12.5
>>>>>>> 68b97470a3a2c32ab85685923bbaeaf47447ec26

cache:
  bundler: true
  directories:
    - vendor/bundle
    - node_modules

env:
  global:
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start' # for gui tests
  - sleep 3 # let xvfb start up

script:
  - npm install
  - psql -c 'create database workbase_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  # run both rspec and cucumber tests
  - bundle exec rake
