# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee848296afbfdc28536d0ac8bc8d31e2be67eef1133b11fe70a741f7f5a62c40fe53d73544a018127d46eb90c5a80590385fe2e84c9617fcb292bbbe7bdccf2b
  hostname: localhost:3000
  enable_mailer: false
  domain: 'gmail.com'
  mailer_username: <%= ENV["MAILER_USERNAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  smtp_address: 'smtp.gmail.com'
  smtp_port: 587

test:
  secret_key_base: f6cf9ebfbade91b91ed524f64802ff2c8f7550fc292307280a46d8732f76de9930e7a616177f08ce29c4682e7b0b09a7a02da3c33f9340faf29de7991fcc320d
  hostname: localhost:3000
  enable_mailer: false

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hostname: workbase-staging.herokuapp.com
  enable_mailer: true
  domain: 'workbase.com'
  mailer_username: <%= ENV["SENDGRID_USERNAME"] %>
  mailer_password: <%= ENV["SENDGRID_PASSWORD"] %>
  smtp_address: 'smtp.sendgrid.net'
  smtp_port: 587
